### ISSUE TITLE
Altitude of Planets and Moon is not Accurate

### ISSUE THREAD

**Issue by shreyasbapat** [shreyasbapat/Alt-Az-Generator#2]
The Altitude for Planets and Moon vary from the actual results by a significant 2-3 degrees.

**Comment by remiberthoz** [comment]
I'm not sure what data source you are comparing your output against. If you are comparing against position in the sky of current day at 00:00, you need to set an epoch for your `obj` and `place` object.

**Comment by shreyasbapat** [comment]
I am comparing with the position in the sky at the exact same time using the software Stellarium

**Comment by remiberthoz** [comment]
Sorry, I can't figure this out entirely. There are many things you need check.

* Do both Stellarium and the library display same celestial coordinates systems? [[see](http://rhodesmill.org/pyephem/radec)]

* Do both use the same corrections? (atmospheric refraction, precession, epoch, etc.) [[see](http://rhodesmill.org/pyephem/quick.html#observers)]

I honestly can't understand your code now, there are a lot of things. I think you should try with a minimal example in another file: fix a date, fix a location, fix a body. Display things one by one and check everything with Stellarium.

When trying to reproduce your code, I find that `obj._ra = o.ra` does not produce consistent number copy: decimals are already mismatching.

You use a `place` and a `test_place`, with different times, but you compute `o` objects with one, and `obj` with another. Is this what you want to do?

**Comment by shreyasbapat** [comment]
Oh! This copy issue needs attention. But I almost fixed the issue.. Other than this, I am still not getting correct results for Moon. I don't know why! I am opening a separate issue for moon, Please open it for the *copy* thing. We will work it out somehow.
I am closing this particular issue.

**Comment by remiberthoz** [comment]
Do you get correct results for planets and stars ?

**Comment by shreyasbapat** [comment]
Yes, accurate till some decimals

**Comment by shreyasbapat** [comment]
You pointed out a good thing. I didn't see this. [This](http://rhodesmill.org/pyephem/radec)
Please open a issue for specifically dealing with this

**Comment by shreyasbapat** [comment]
I dont think this is happening. 

> Enter the name of object: Moon
>Just for Test obj._ra23:05:25.58
>Just for Test o.ra23:05:25.58
>Resultant Altitude: 49.21978091393217
>Resultant Azimuth: 189.86423251018044
This is what I got. Please elaborate your issue

**Comment by remiberthoz** [comment]
If you get good results for planets, but not for the Moon, it might be because the Moon position is not easy to define. Is it by it's geometric center, it's apparent geometrical center, it's gravity center? I think Stellarium uses a particular crater. The Moon being big, that could make the difference.

**Comment by shreyasbapat** [comment]
@TiiXel I guess you are right. But what are your thoughts on this - Even if we consider that Stellarium and PyEphem chooses two completely opposite points on the moon, what can be the maximum error or maybe you can say the difference between both the results?

**Comment by remiberthoz** [comment]
The Moon is half a degree in apparent size.

**Comment by shreyasbapat** [comment]
Yeah! This is my point exactly. I am observing a 2-3 degree difference.

**Comment by remiberthoz** [comment]
Is Stellarium displaying topocentric coordinates?

**Comment by shreyasbapat** [comment]
No...

**Comment by remiberthoz** [comment]
PyEphem does!

**Comment by shreyasbapat** [comment]
I guess I have figured out the issue. Thanks @TiiXel  Everything is fine now. :)
