### ISSUE TITLE
Alt Az of Moon from this does not match with Stellarium

### ISSUE THREAD

**Issue by shreyasbapat** [shreyasbapat/Alt-Az-Generator#4]
The Data for moon is not matching.

**Comment by rtanmay** [comment]
I think the data won't match because the time is 00:00:00. It is not taking the correct UTC(Coordinated Universal Time).
So, the data of not only moon but also of any other object won't match as the time is not correct.

**Comment by rtanmay** [comment]
Issue is solved, 
I have created the Pull Request.

Details are in the PR.

**Comment by shreyasbapat** [comment]
Data of each and every object is matching. And probably of the moon too. Time corrections are not required. Just in case you want to check it, verify it with Stellarium
