### ISSUE TITLE
The program does not check if the entered object is in the database or not

### ISSUE THREAD

**Issue by rtanmay** [shreyasbapat/Alt-Az-Generator#5]
Also, Status of the object is not shown when it is above the Horizon.

**Comment by rtanmay** [comment]
Have created the Pull Request.

**Comment by shreyasbapat** [comment]
Check thi with the output of stellarium first :)

**Comment by shreyasbapat** [comment]
@rtanmay  Check this issue #2 first. And then again make changes accordingly. :)

**Comment by rtanmay** [comment]
@shreyasbapat Thanks for the reference :)
