### ISSUE TITLE
Write unit tests for SkyStars class methods! 

### ISSUE THREAD

**Issue by shreyasbapat** [shreyasbapat/Alt-Az-Generator#8]
🐞 **Problem**

🖥 **Please paste the output of following commands**

🎯 **Goal**

💡 **Possible solutions**

📋  **Steps to solve the problem**

 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request and add this in comments - `Addresses #<put issue number here>`
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

**Comment by illright** [comment]
I'll do it. Should I test all classes or just `SkyStars`?

**Comment by shreyasbapat** [comment]
Just skystars!

**Comment by shreyasbapat** [comment]
Closed in #10
